use_frameworks!

target 'KeyStorage_Example' do
  pod 'KeyStorage', :path => '../'

  target 'KeyStorage_Tests' do
    inherit! :search_paths
    pod 'KeyStorage', :path => '../'
    pod 'Nimble', '~> 5.0.0'

  end
end
